---
name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use pyinstall to create distribution binary
      run: pyinstaller -F router_registration_bootstrap.py
    #- name: Use pyinstall to create distribution binary
    #  run: pyinstaller -F router_reg.py
    - name: version
      #run: echo "::set-output name=version::$(./dist/router_reg -v)"
      run: echo "::set-output name=version::$(echo 4.2.2)"
      id: version
      
    - name: Tar bootstrap
      # tar with a dash in the name for backwards compatibility
      run: cd dist; mv router_registration_bootstrap router-registration; tar -zcvf router_registration_bootstrap.tar.gz router-registration
    #- name: Tar registration script
    #  run: cd dist; mv router_reg .router_reg; tar -zcvf router_registration.tar.gz .router_reg
    - name: release
      uses: actions/create-release@v1
      id: release
      with:
        draft: false
        prerelease: false
        release_name: v${{ steps.version.outputs.version }}
        tag_name: v${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload registration bootstrap release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/router_registration_bootstrap.tar.gz
        asset_name: router_registration_bootstrap.tar.gz
        asset_content_type: application/gzip

#    - name: Upload registration script release
#      uses: actions/upload-release-asset@v1
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
#      with:
#        upload_url: ${{ steps.release.outputs.upload_url }}
#        asset_path: dist/router_registration.tar.gz
#        asset_name: router_registration.tar.gz
#        asset_content_type: application/gzip
