---
name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Use pyinstall to create router_registration_bootstrap distribution binary
      run: pyinstaller -F router_registration_bootstrap.py
    - name: Use pyinstall to create router_registration distribution binary
      run: pyinstaller -F router_registration.py      
    - name: Use pyinstall to create ziti_router_auto_enroll distribution binary
      run: pyinstaller -F ziti_router_auto_enroll/ziti_router_auto_enroll.py      

    - name: version
      run: echo "version=$(./dist/router_registration -v)" >> $GITHUB_ENV
      id: version
      
    - name: Tar bootstrap
      # tar with a dash in the name for backwards compatibility
      run: cd dist; mv router_registration_bootstrap router-registration; tar -zcvf router_registration_bootstrap.tar.gz router-registration

    - name: Tar router registration
      # tar with a . in the name for backwards compatibility
      run: cd dist; mv router_registration .router_registration; tar -zcvf router_registration.tar.gz .router_registration

    - name: Tar ziti router auto enroll
      run: cd dist; tar -zcvf ziti_router_auto_enroll.tar.gz ziti_router_auto_enroll

    - name: release
      uses: actions/create-release@v1
      id: release
      with:
        draft: false
        prerelease: false
        release_name: v${{ env.version }}
        tag_name: v${{ env.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload registration bootstrap release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/router_registration_bootstrap.tar.gz
        asset_name: router_registration_bootstrap.tar.gz
        asset_content_type: application/gzip

    - name: Upload router_registration
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/router_registration.gz
        asset_name: router_registration.tar.gz
        asset_content_type: application/gzip

    - name: Upload ziti_router_auto_enroll
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: dist/ziti_router_auto_enroll.tar.gz
        asset_name: ziti_router_auto_enroll.tar.gz
        asset_content_type: application/gzip
